In [42]:
using Plots
plotly()

Plots.PlotlyBackend()

1. Random Walks

1a. Random Markov Matrix (Definition of Markov: rows sum to 1, every element between 0 and 1)

In [309]:
# create a matrix of probabilities
# P[i,j] is the probability of going from i to j
n = 5
P = rand(1:5,n,n)
P = P ./ sum(P,2) 

5×5 Array{Float64,2}:
 0.416667   0.0833333  0.0833333  0.166667  0.25    
 0.294118   0.235294   0.117647   0.176471  0.176471
 0.0833333  0.0833333  0.416667   0.25      0.166667
 0.133333   0.333333   0.2        0.133333  0.2     
 0.176471   0.294118   0.0588235  0.235294  0.235294

In [310]:
C = cumsum(P,2)
function take_walk(C, steps=200)
    walk = [rand(1:n)]
    for i=1:(steps-1)
        push!(walk, 1+sum(rand().> C[walk[i],:] ))    
    end
    return(walk)
end

take_walk (generic function with 3 methods)

In [311]:
steps = 200_000
histogram( take_walk(C,steps))

In [347]:
function predicted(P,steps)
  b = find(eigvals(P') .≈ 1)
  π = steps * normalize(abs.(eigvecs(P')[:,b])[:],1)
end

predicted (generic function with 1 method)

In [348]:
predicted(P,steps)

18-element Array{Float64,1}:
 11114.0
 11105.0
 11108.5
 11093.8
 11079.2
 11117.6
 11091.4
 11146.5
 11145.8
 11098.4
 11080.4
 11141.0
 11145.7
 11106.3
 11095.5
 11098.8
 11118.3
 11113.8

1b. Pagerank Matrix

In [326]:
n = 18
A = rand(0:1,n,n)

18×18 Array{Int64,2}:
 0  0  1  1  0  0  0  0  1  1  0  0  1  1  1  0  1  1
 0  1  0  1  0  1  1  1  0  0  1  1  1  0  1  1  0  0
 1  1  1  1  1  1  0  0  0  1  0  1  0  1  0  1  0  1
 1  1  1  0  0  1  0  1  1  0  1  0  1  1  0  1  1  0
 1  1  1  0  1  0  1  1  1  0  0  0  0  1  0  1  1  1
 1  0  0  1  1  0  0  1  0  1  0  1  1  0  0  1  1  0
 0  1  1  0  0  1  0  1  0  0  0  0  1  1  1  0  0  0
 0  0  0  0  1  1  1  1  1  0  1  1  0  0  0  1  1  1
 1  0  1  0  0  1  1  0  0  1  0  1  1  0  1  0  1  1
 1  0  0  0  0  1  0  1  1  1  0  1  1  1  1  0  0  0
 0  1  0  0  1  0  0  1  1  0  1  1  1  0  0  0  1  0
 1  1  0  1  1  0  1  0  0  0  1  1  1  1  1  1  0  1
 1  0  1  0  0  0  1  0  1  1  0  1  1  0  0  0  0  1
 1  0  0  1  0  0  1  0  1  0  0  1  1  1  0  1  0  1
 0  0  1  1  0  0  0  1  1  1  1  0  0  1  0  0  1  0
 0  0  1  0  0  1  0  1  1  0  1  1  1  0  1  0  1  1
 1  1  0  1  1  1  1  1  1  1  0  0  0  0  0  0  0  0
 0  1  0  0  0  1  0  1  1  0  0  1  0  0  1  1  1  1

In [332]:
A = A ./ sum(A,2)
d = .1
P = (1-d).*A + d.*ones(n,n)./n
C = cumsum(P,2)

18×18 Array{Float64,2}:
 0.00555556  0.0111111  0.116667   …  0.783333  0.788889  0.894444  1.0
 0.00555556  0.101111   0.106667      0.893333  0.988889  0.994444  1.0
 0.0873737   0.174747   0.262121      0.819697  0.907071  0.912626  1.0
 0.0873737   0.174747   0.262121      0.819697  0.907071  0.994444  1.0
 0.0873737   0.174747   0.262121      0.737879  0.825253  0.912626  1.0
 0.105556    0.111111   0.116667   …  0.783333  0.888889  0.994444  1.0
 0.00555556  0.139683   0.27381       0.983333  0.988889  0.994444  1.0
 0.00555556  0.0111111  0.0166667     0.713333  0.808889  0.904444  1.0
 0.0955556   0.101111   0.196667      0.803333  0.808889  0.904444  1.0
 0.105556    0.111111   0.116667      0.983333  0.988889  0.994444  1.0
 0.00555556  0.123611   0.129167   …  0.870833  0.876389  0.994444  1.0
 0.0805556   0.161111   0.166667      0.833333  0.913889  0.919444  1.0
 0.118056    0.123611   0.241667      0.870833  0.876389  0.881944  1.0
 0.105556    0.111111   0.116667      0.

In [333]:
steps = 200_000
histogram( take_walk(C,steps))

In [335]:
using Interact

In [346]:
@manipulate for d=0:.01:.99
  P = (1-d).*A + d.*ones(n,n)./n
  ev = predicted(P,steps)
  plot(ev,ylim=(0,maximum(ev)))
end

Interact.Options{:SelectionSlider,Float64}(23: "input-7" = 0.49 Float64 , "d", 0.49, "0.49", Interact.OptionDict(DataStructures.OrderedDict("0.0"=>0.0,"0.01"=>0.01,"0.02"=>0.02,"0.03"=>0.03,"0.04"=>0.04,"0.05"=>0.05,"0.06"=>0.06,"0.07"=>0.07,"0.08"=>0.08,"0.09"=>0.09…), Dict(0.54=>"0.54",0.86=>"0.86",0.09=>"0.09",0.35=>"0.35",0.22=>"0.22",0.38=>"0.38",0.56=>"0.56",0.2=>"0.2",0.89=>"0.89",0.06=>"0.06"…)), Any[], Any[], true, "horizontal")

1c. Metropolis:  An inverse problem, given the distribution (the eigenvector) construct a convenient matrix.

Important step to understanding Bayesian learning simulations. With Stan https://arxiv.org/pdf/1701.02434.pdf  being the best.  You will see fancier variants like Hamiltonian MCMC: https://arxiv.org/pdf/1701.02434.pdf but let's take baby steps today. For some perspective perhaps read http://fastml.com/bayesian-machine-learning/ .

In [1]:
# Create a vector of Probabilities (the eigenvector)
n = 5
π = normalize(rand(n),1)

5-element Array{Float64,1}:
 0.131776
 0.203156
 0.114517
 0.15858 
 0.391971

Given a vector of probabilities $\pi$ a matrix is said to be detailed balance with respect to $\pi$ if any of the following equivalent conditions hold:

In [38]:
# P.*π = P'.*π' (Must explain BROADCAST)
#P./π' = P'./π    (0/0 is a wildcard)
# [π[i]*P[i,j] for i=1:n,j=1:n] ≈ [π[j]*P[j,i] for i=1:n,j=1:n]
# P' = Diagonal(π)*P*Diagonal(1./π)  (hence P is diagonally similar to P')
# Diagonal(sqrt.(π)) * P * Diagonal(sqrt.(1./π)) is symmetric

The metropolis construction of a detailed balance matrix given π:

In [3]:
# The Metropolis thing creates P from π
P = min.(1,π'./π)/n;
for i=1:n P[i,i] += 1-sum(P[i,:]) end

In [39]:
# Test 1
P.*π ≈ P'.*π' 

true

In [41]:
# Test 2
P./π' ≈ P'./π 

true

In [42]:
# Test 3
[π[i]*P[i,j] for i=1:n,j=1:n] ≈ [π[j]*P[j,i] for i=1:n,j=1:n]

true

In [43]:
# Test 4
P' ≈ Diagonal(π)*P*Diagonal(1./π) 

true

In [52]:
# Test 5
S = Diagonal(sqrt.(π)) * P * Diagonal(sqrt.(1./π))
norm(S - S')

9.714451465470122e-17

IsSymmetric needs a tolerance!

Symmetric matrices: right eigenvectors are left eigenvectors

Detailed balance matries: left eigenvectors are π.*right eigenvectors (diag scaling)

In [104]:
X = eigvecs(P)
Y = eigvecs(P')
(Y ./ (π.*X))  .* (abs.(Y).>1e-7) # 0/0 is annoying

5×5 Array{Float64,2}:
 4.46731  3.70536   5.63514   8.18048   6.95782
 4.46731  3.70536   5.63514  -0.0      -0.0    
 4.46731  3.70536   5.63514   8.18048   6.95782
 4.46731  3.70536   5.63514   0.0       6.95782
 4.46731  3.70536  -0.0       0.0      -0.0    